package com.sauceless.item.advancement;

public class advProgression {
    public String[] boost = {
            "nether/uneasy_alliance",
            "nether/netherite_armor",
            "nether/ride_strider_in_overworld_lava",
            "nether/explore_nether",
            "nether/all_potions",
            "nether/all_effects",
            "end/levitate",
            "adventure/fall_from_world_height",
            "adventure/hero_of_the_village",
            "adventure/kill_all_mobs",
            "adventure/trade_at_world_height",
            "adventure/trim_with_all_exclusive_armor_patterns",
            "adventure/two_birds_one_arrow",
            "adventure/arbalistic",
            "adventure/craft_decorated_pot_using_only_sherds",
            "adventure/adventuring_time",
            "adventure/spyglass_at_dragon",
            "adventure/very_very_frightening",
            "adventure/sniper_duel",
            "adventure/bullseye",
            "adventure/brush_armadillo",
            "adventure/minecraft_trials_edition",
            "adventure/who_needs_rockets",
            "adventure/under_lock_and_key",
            "adventure/revaulting",
            "adventure/blowback",
            "adventure/overoverkill",
            "husbandry/ride_a_boat_with_a_goat",
            "husbandry/obtain_sniffer_egg",
            "husbandry/bred_all_animals",
            "husbandry/allay_deliver_cake_to_note_block",
            "husbandry/complete_catalogue",
            "husbandry/leash_all_frog_variants",
            "husbandry/feed_snifflet",
            "husbandry/balanced_diet",
            "husbandry/obtain_netherite_hoe",
            "husbandry/froglights",
            "husbandry/kill_axolotl_target",
            "husbandry/whole_pack",
    };
}
